version: '2'
services:
  backend:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: koa2_docker
    env_file: .env
    environment:
      - NODE_ENV = "production"
    ports:
      - 9000:9000
    entrypoint: ["npm", "start"]
