version: '2'
services:
  koa2:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: koa2_docker
    environment:
      NODE_ENV: "production"
    ports:
      - "80:9000"
    entrypoint: ["npm", "start"]
