FROM node:latest

ADD package.json /tmp/package.json
RUN cd /tmp && npm install && mkdir -p /usr/src/app/node_modules/
RUN cp -a /tmp/node_modules /usr/src/app/
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app

CMD [ "npm", "start" ]
