version: '2'

services:
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: koa-prod-backend
    image: joonadocker/reactcourse
    environment:
      NODE_ENV: "production"
    volumes:
      - "./src:/usr/src"
    ports:
      - "80:9000"
    entrypoint: ["npm", "start"]