version: '2'
services:
  backend:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: koa2_docker
    environment:
      NODE_ENV: "production"
    ports:
      - 9000:9000
    entrypoint: ["npm", "start"]
